### ISSUE TITLE
Bug: Does not see all devices

### ISSUE THREAD

**Issue by tomswinkels** [WebProject-xyz/ikea-tradfri-php#22]
I don't see my light bulps.

When i use: `$group->getLights();` the response is empty.

When i use: `$group->getDevices();` i only see my sensor.

When i run: 

`coap-client -m get -u "php-api-user" -k "<apikey>" "coaps://<remoteip>:5684/15001/65537"
`
This is my response:

```
v:1 t:CON c:GET i:6336 {} [ ]
decrypt_verify(): found 24 bytes cleartext
decrypt_verify(): found 249 bytes cleartext
{"9001":"TRADFRI bulb GU10 W 400lm","9002":1545681498,"9020":1545767907,"9003":65537,"9054":0,"5750":2,"9019":1,"3":{"0":"IKEA of Sweden","1":"TRADFRI bulb GU10 W 400lm","2":"","3":"1.2.214","6":1},"3311":[{"5850":0,"5851":254,"9003":0}]}
```

**Comment by Fahl-Design** [comment]
I added the lamp type with name "TRADFRI bulb GU10 W 400lm" and removed error suppression 

if you run `wiki/example/example-list-devices.php` you should see all your devices or get an "unknown device type" error. I think i will optimize the device detection later on

**Comment by robbanl** [comment]
I have the same issue. Currently using the branch "feature/replace_coap_command_class" to have my lamps working.

**Comment by robbanl** [comment]
Some more devices that should be added:

"TRADFRI Driver 10W" - https://www.ikea.com/se/sv/catalog/products/50356187/
"TRADFRI Driver 30W" - https://www.ikea.com/se/sv/catalog/products/60342656/
"TRADFRI bulb E14 W op/ch 400lm" - https://www.ikea.com/se/sv/catalog/products/60365271/

Getting some more devices tonight so I can add them also if they are missing.

Would you like me to do a pull request to `replace_coap_command_class` branch?

**Comment by Fahl-Design** [comment]
> Some more devices that should be added:
> 
> "TRADFRI Driver 10W" - https://www.ikea.com/se/sv/catalog/products/50356187/
> "TRADFRI Driver 30W" - https://www.ikea.com/se/sv/catalog/products/60342656/
> "TRADFRI bulb E14 W op/ch 400lm" - https://www.ikea.com/se/sv/catalog/products/60365271/
> 
> Getting some more devices tonight so I can add them also if they are missing.
> 
> Would you like me to do a pull request to `replace_coap_command_class` branch?

Hi, feel free to edit what you like :) 
I will work on it as soon as I have some spare time. Next weekend I guess
